### ISSUE TITLE
Mac upgrade breaks fermi-ware compile

### ISSUE THREAD

**Issue by ezcrues** [nasa/trick#1057]
Just upgrade to latest MacOS X 10.15.7 and the latest Xcode 12.0.1.  The fermi-ware software is not C99 compliant:

XY.c:643:6: error: implicit declaration of function '_XmDrawShadow' is invalid in C99 [-Werror,-Wimplicit-function-declaration]
     _XmDrawShadow (XtDisplay(w), XtWindow(w), w->primitive.bottom_shadow_GC,
     ^
XY.c:651:6: error: implicit declaration of function '_XmHighlightBorder' is invalid in C99 [-Werror,-Wimplicit-function-declaration]
     _XmHighlightBorder((Widget)w);
     ^
XY.c:652:14: error: implicit declaration of function '_XmDifferentBackground' is invalid in C99 [-Werror,-Wimplicit-function-declaration]
    else if (_XmDifferentBackground((Widget)w, XtParent((Widget)w)))
             ^
XY.c:653:6: error: implicit declaration of function '_XmUnhighlightBorder' is invalid in C99 [-Werror,-Wimplicit-function-declaration]
     _XmUnhighlightBorder((Widget)w);
     ^
XY.c:653:6: note: did you mean '_XmHighlightBorder'?
XY.c:651:6: note: '_XmHighlightBorder' declared here
     _XmHighlightBorder((Widget)w);
     ^
4 errors generated.
make[2]: *** [object_Darwin_19/XY.o] Error 1
make[1]: *** [fermi-ware] Error 2

**Comment by alexlin0** [comment]
I have confirmed this error and I am using Xcode 12.0.0

**Comment by alexlin0** [comment]
From https://developer.apple.com/documentation/xcode-release-notes/xcode-12-release-notes

> Clang now reports an error when you use a function without an explicit declaration when building C or Objective-C code for macOS (-Werror=implicit-function-declaration flag is on). This additional error detection unifies Clang’s behavior for iOS/tvOS and macOS 64-bit targets for this diagnostic. (49917738)

So this is new behavior that we have to address now.

**Comment by spfennell** [comment]
@ezcrues 
@alexlin0 

The makefile for fermi-ware has been updated and 19.2.0f has been re-released. 

We don't maintain fermi-ware, but we do maintain the makefile, located in fermi-ware. I added the
`-Wno-implicit-function-declaration` flag :
```
ifeq ($(TRICK_HOST_TYPE), Darwin)
       DP_CFLAGS += -I/sw/include -Wno-implicit-function-declaration
endif
```

You can edit the makefile yourself or find the new release/fermi-ware directory in the newly updated release 19.2.0f.

Also, don't forget to check out https://github.com/nasa/koviz 
Koviz is a great Trick simulation data plotting, visualization and analysis tool, and is currently maintained

**Comment by alexlin0** [comment]
I pushed the above fix into the fermi-ware repository.

**Comment by spfennell** [comment]
reopening to update cmakelists.txt

**Comment by ezcrues** [comment]
I just tried the latest and it does not fit the issue for me.  I still get the same original errors.

**Comment by ezcrues** [comment]
If I replace the '-Wall' in the fermi-ware makefile with '-w', then is builds.  Admittedly a bit dangerous.  There is probably a less intrusive approach but it does work.

**Comment by spfennell** [comment]
> I just tried the latest and it does not fit the issue for me. I still get the same original errors.

@ezcrues Interesting, the -Wno-implicit-function-declaration worked for me on Catalina with Xcode 12. You do have that flag in your makefile?

**Comment by alexlin0** [comment]
did you git pull in the fermi-ware directory.  Pulling in the Trick directory does not update the fermi-ware directory, even with the recursive flag.

**Comment by ezcrues** [comment]
@spfennell , I just cleaned and tried it again.  No joy.  I even made sure to pull the latest.  I checked the fermi-ware makefile and '-Wno-implicit-function-declaration' doesn't appear anywhere in the file.

**Comment by ezcrues** [comment]
I am running Mac OS X 10.15.7 and Xcode 12.0.1.

**Comment by spfennell** [comment]
> @spfennell , I just cleaned and tried it again. No joy. I even made sure to pull the latest. I checked the fermi-ware makefile and '-Wno-implicit-function-declaration' doesn't appear anywhere in the file.

The change is in two places. The fermi-ware release on ESGL and the latest trick release on ESGL (19.0.2f). The change resides in the fermi-ware directory, which is not on github.com

**Comment by ezcrues** [comment]
Okay, my fermi-ware points to

       url = https://developer.nasa.gov/alin/fermi-ware
       fetch = +refs/heads/*:refs/remotes/origin/*

Where should it point?  Why is this different than what is on GitHub?

**Comment by spfennell** [comment]
@ezcrues update your pointer to the esgl repo. We can no longer update the repo on developer.nasa.gov. 
Fermi-ware is not on github, because it is not open source. I will email you the esgl repo.

**Comment by ezcrues** [comment]
Well, that explains it.  Yes, please email me the repo path.

Thanks!

**Comment by ezcrues** [comment]
Seems to be working now.  Thanks!
