### ISSUE TITLE
Simulation works but Trick View not updated in Viewing Real-Time Data with Trick View (TV) Tutorial

### ISSUE THREAD

**Issue by Fjolnirr** [nasa/trick#1409]
Hi,
I was following the trick tutorial and in the [**"Viewing Real-Time Data with Trick View (TV)"**](https://nasa.github.io/trick/tutorial/ATutTrickView) section i am stuck at the ***7th*** step.<br />    Which is ;
**->**_7. On the sim control panel, click the Start button to put the simulation into action. Notice that TV parameter values have changed. When the simulation time reaches 2.0 seconds, the cannon ball position will be [86.17, 30.33]._ <br />
However as you can see in the image below even though my simulation stops at the sec 2.0 There is no update on the Trick View, no value changes or simulation time changes. Am I missing something? Could you please help me?<br />
![bug](https://user-images.githubusercontent.com/40665614/204540012-09c8af9d-6592-433a-9ae5-43adbf84fcf1.PNG)

Edit: Also on run-time cmd prompts this messages; 
```	at java.base/jdk.internal.math.FloatingDecimal.readJavaFormatString(FloatingDecimal.java:1842)
	at java.base/jdk.internal.math.FloatingDecimal.parseDouble(FloatingDecimal.java:110)
	at java.base/java.lang.Double.parseDouble(Double.java:543)
	at trick.common.utils.vs.VSDouble.fromVariableServer(VSDouble.java:15)
	at trick.common.utils.vs.Variable.setValue(Variable.java:129)
	at trick.common.utils.vs.VariableTracker.process(VariableTracker.java:109)
	at java.desktop/javax.swing.SwingWorker$3.run(SwingWorker.java:423)
	at java.desktop/sun.swing.AccumulativeRunnable.run(AccumulativeRunnable.java:112)
	at java.desktop/javax.swing.SwingWorker$DoSubmitAccumulativeRunnable.run(SwingWorker.java:847)
	at java.desktop/sun.swing.AccumulativeRunnable.run(AccumulativeRunnable.java:112)
	at java.desktop/javax.swing.SwingWorker$DoSubmitAccumulativeRunnable.actionPerformed(SwingWorker.java:857)
	at java.desktop/javax.swing.Timer.fireActionPerformed(Timer.java:317)
	at java.desktop/javax.swing.Timer$DoPostEvent.run(Timer.java:249)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:313)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:770)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:715)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:740)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
Exception in thread "AWT-EventQueue-0" java.lang.NumberFormatException: empty String
```

**Comment by jdeans289** [comment]
I was able to reproduce this. We'll get a fix out asap

**Comment by spfennell** [comment]
@Fjolnirr we are working on this, a temporary workaround is to use Trick 19.4 instead of master/19.5

**Comment by jdeans289** [comment]
Hi @Fjolnirr , we've released a patch for this issue on master and in release 19.5.1. Please update and rebuild Trick. Thanks for pointing this out!

**Comment by Fjolnirr** [comment]
Hi @jdeans289 I have checkout to the release 19.5.1 and rebuild the Trick. However, I am still getting the same results. Any hints?
